(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (incorrect-password dummy)
    "Incorrect password")
  (define (dispatch givenpw m)
    (cond ((not (eq? givenpw password)) incorrect-password)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUN"
                       m))))
  dispatch)

(define (make-joint original-account original-password joint-password)
  (lambda (given-password m)
    (if (eq? given-password joint-password)
        (original-account original-password m)
        "Incorrect password")))

(define peter-acc (make-account 100 'open-sesame))
(define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))

((paul-acc 'rosebud 'withdraw) 10)
((peter-acc 'open-sesame 'deposit) 20)
((peter-acc 'open-sesame 'withdraw) 15)
((paul-acc 'rosebud 'deposit) 20)
